# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Set library preference based on BUILD_SHARED_LIBS
#
if( BUILD_SHARED_LIBS)
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
else()
   set( MULLE_PREFERRED_LIBRARY_PREFIX "${CMAKE_STATIC_LIBRARY_PREFIX}")
   set( MULLE_PREFERRED_LIBRARY_SUFFIX "${CMAKE_STATIC_LIBRARY_SUFFIX}")
   set( MULLE_FALLBACK_LIBRARY_PREFIX "${CMAKE_SHARED_LIBRARY_PREFIX}")
   set( MULLE_FALLBACK_LIBRARY_SUFFIX "${CMAKE_SHARED_LIBRARY_SUFFIX}")
endif()

#
# Generated from sourcetree: B35D4BC6-54DD-494E-B83E-7A52C16C8A1F;mulle-allocator;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import,no-singlephase;mulle-core,mulle-allocator
# Disable with : `mulle-sourcetree mark mulle-allocator no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-allocator no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-allocator no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-core")
else()
   if( NOT MULLE__ALLOCATOR_LIBRARY)
      foreach( _TMP_MULLE__ALLOCATOR_LIBRARY_TARGET mulle-core mulle-allocator)
         if( TARGET ${_TMP_MULLE__ALLOCATOR_LIBRARY_TARGET})
            set( MULLE__ALLOCATOR_LIBRARY ${_TMP_MULLE__ALLOCATOR_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__ALLOCATOR_LIBRARY)
         find_library( MULLE__ALLOCATOR_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-core
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-allocator
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__ALLOCATOR_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__ALLOCATOR_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-core
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-allocator
            )
         endif()
      endif()
      message( STATUS "MULLE__ALLOCATOR_LIBRARY is ${MULLE__ALLOCATOR_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__ALLOCATOR_LIBRARY)
         #
         # Add MULLE__ALLOCATOR_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-allocator no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__ALLOCATOR_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-allocator no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__ALLOCATOR_ROOT "${MULLE__ALLOCATOR_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__ALLOCATOR_ROOT "${_TMP_MULLE__ALLOCATOR_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-allocator no-cmake-dependency`
         #
         foreach( _TMP_MULLE__ALLOCATOR_NAME "mulle-core" "mulle-allocator")
            set( _TMP_MULLE__ALLOCATOR_DIR "${_TMP_MULLE__ALLOCATOR_ROOT}/include/${_TMP_MULLE__ALLOCATOR_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__ALLOCATOR_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__ALLOCATOR_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__ALLOCATOR_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__ALLOCATOR_DIR}")
               #
               unset( MULLE__ALLOCATOR_DEFINITIONS)
               unset( MULLE__ALLOCATOR_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__ALLOCATOR_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__ALLOCATOR_DEFINITIONS})
               include( "${_TMP_MULLE__ALLOCATOR_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__ALLOCATOR_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__ALLOCATOR_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-allocator no-require-link`
         message( SEND_ERROR "MULLE__ALLOCATOR_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-core
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-allocator${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-allocator${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-allocator")
      endif()
   endif()
endif()


#
# Generated from sourcetree: 59E34F3E-49F3-442A-99F9-9F737CE6B733;mulle-dlfcn;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import,no-public,no-singlephase;mulle-core,mulle-dlfcn
# Disable with : `mulle-sourcetree mark mulle-dlfcn no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-dlfcn no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-dlfcn no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-core")
else()
   if( NOT MULLE__DLFCN_LIBRARY)
      foreach( _TMP_MULLE__DLFCN_LIBRARY_TARGET mulle-core mulle-dlfcn)
         if( TARGET ${_TMP_MULLE__DLFCN_LIBRARY_TARGET})
            set( MULLE__DLFCN_LIBRARY ${_TMP_MULLE__DLFCN_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__DLFCN_LIBRARY)
         find_library( MULLE__DLFCN_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-core
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-dlfcn
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__DLFCN_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__DLFCN_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-core
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-dlfcn
            )
         endif()
      endif()
      message( STATUS "MULLE__DLFCN_LIBRARY is ${MULLE__DLFCN_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__DLFCN_LIBRARY)
         #
         # Add MULLE__DLFCN_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-dlfcn no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__DLFCN_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-dlfcn no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__DLFCN_ROOT "${MULLE__DLFCN_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__DLFCN_ROOT "${_TMP_MULLE__DLFCN_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-dlfcn no-cmake-dependency`
         #
         foreach( _TMP_MULLE__DLFCN_NAME "mulle-core" "mulle-dlfcn")
            set( _TMP_MULLE__DLFCN_DIR "${_TMP_MULLE__DLFCN_ROOT}/include/${_TMP_MULLE__DLFCN_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__DLFCN_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__DLFCN_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__DLFCN_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__DLFCN_DIR}")
               #
               unset( MULLE__DLFCN_DEFINITIONS)
               unset( MULLE__DLFCN_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__DLFCN_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__DLFCN_DEFINITIONS})
               include( "${_TMP_MULLE__DLFCN_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__DLFCN_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__DLFCN_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-dlfcn no-require-link`
         message( SEND_ERROR "MULLE__DLFCN_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-core
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-dlfcn${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-dlfcn${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-dlfcn")
      endif()
   endif()
endif()


#
# Generated from sourcetree: 89FAB433-A023-45D6-89A2-96047B6D7602;mulle-thread;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import,no-singlephase;mulle-core,mulle-thread
# Disable with : `mulle-sourcetree mark mulle-thread no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-thread no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-thread no-cmake-sdk-<name>`
#
if( COLLECT_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND DEPENDENCY_LIBRARIES "mulle-core")
else()
   if( NOT MULLE__THREAD_LIBRARY)
      foreach( _TMP_MULLE__THREAD_LIBRARY_TARGET mulle-core mulle-thread)
         if( TARGET ${_TMP_MULLE__THREAD_LIBRARY_TARGET})
            set( MULLE__THREAD_LIBRARY ${_TMP_MULLE__THREAD_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__THREAD_LIBRARY)
         find_library( MULLE__THREAD_LIBRARY NAMES
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-core
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${MULLE_PREFERRED_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
            ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${MULLE_FALLBACK_LIBRARY_SUFFIX}
            mulle-thread
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__THREAD_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__THREAD_LIBRARY NAMES
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-core
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${MULLE_PREFERRED_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
               ${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${MULLE_FALLBACK_LIBRARY_SUFFIX}
               mulle-thread
            )
         endif()
      endif()
      message( STATUS "MULLE__THREAD_LIBRARY is ${MULLE__THREAD_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__THREAD_LIBRARY)
         #
         # Add MULLE__THREAD_LIBRARY to DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-thread no-cmake-add`
         #
         list( APPEND DEPENDENCY_LIBRARIES ${MULLE__THREAD_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-thread no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__THREAD_ROOT "${MULLE__THREAD_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__THREAD_ROOT "${_TMP_MULLE__THREAD_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-thread no-cmake-dependency`
         #
         foreach( _TMP_MULLE__THREAD_NAME "mulle-core" "mulle-thread")
            set( _TMP_MULLE__THREAD_DIR "${_TMP_MULLE__THREAD_ROOT}/include/${_TMP_MULLE__THREAD_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__THREAD_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__THREAD_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__THREAD_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__THREAD_DIR}")
               #
               unset( MULLE__THREAD_DEFINITIONS)
               unset( MULLE__THREAD_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__THREAD_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__THREAD_DEFINITIONS})
               include( "${_TMP_MULLE__THREAD_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__THREAD_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__THREAD_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-thread no-require-link`
         message( SEND_ERROR "MULLE__THREAD_LIBRARY was not found in ${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-core${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-core${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-core
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_PREFERRED_LIBRARY_PREFIX}mulle-thread${MULLE_PREFERRED_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${CMAKE_DEBUG_POSTFIX}${MULLE_FALLBACK_LIBRARY_SUFFIX}
${MULLE_FALLBACK_LIBRARY_PREFIX}mulle-thread${MULLE_FALLBACK_LIBRARY_SUFFIX}
mulle-thread")
      endif()
   endif()
endif()


#
# Generated from sourcetree: 46AB981C-7796-414D-8B52-984F69957F6F;mulle-atinit;no-cmake-loader,no-cmake-searchpath,no-dynamic-link,no-import,no-intermediate-link,no-singlephase;mulle-core-all-load,mulle-atinit
# Disable with : `mulle-sourcetree mark mulle-atinit no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-atinit no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-atinit no-cmake-sdk-<name>`
#
if( COLLECT_STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES "mulle-core-all-load")
else()
   if( NOT MULLE__ATINIT_LIBRARY)
      foreach( _TMP_MULLE__ATINIT_LIBRARY_TARGET mulle-core-all-load mulle-atinit)
         if( TARGET ${_TMP_MULLE__ATINIT_LIBRARY_TARGET})
            set( MULLE__ATINIT_LIBRARY ${_TMP_MULLE__ATINIT_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__ATINIT_LIBRARY)
         find_library( MULLE__ATINIT_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_STATIC_LIBRARY_SUFFIX}
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__ATINIT_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__ATINIT_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_STATIC_LIBRARY_SUFFIX}
            )
         endif()
      endif()
      message( STATUS "MULLE__ATINIT_LIBRARY is ${MULLE__ATINIT_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__ATINIT_LIBRARY)
         #
         # Add MULLE__ATINIT_LIBRARY to STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-add`
         #
         list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE__ATINIT_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__ATINIT_ROOT "${MULLE__ATINIT_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__ATINIT_ROOT "${_TMP_MULLE__ATINIT_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-atinit no-cmake-dependency`
         #
         foreach( _TMP_MULLE__ATINIT_NAME "mulle-core-all-load" "mulle-atinit")
            set( _TMP_MULLE__ATINIT_DIR "${_TMP_MULLE__ATINIT_ROOT}/include/${_TMP_MULLE__ATINIT_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__ATINIT_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__ATINIT_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__ATINIT_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__ATINIT_DIR}")
               #
               unset( MULLE__ATINIT_DEFINITIONS)
               unset( MULLE__ATINIT_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__ATINIT_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__ATINIT_DEFINITIONS})
               include( "${_TMP_MULLE__ATINIT_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__ATINIT_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__ATINIT_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-atinit no-require-link`
         message( SEND_ERROR "MULLE__ATINIT_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atinit${CMAKE_STATIC_LIBRARY_SUFFIX}")
      endif()
   endif()
endif()


#
# Generated from sourcetree: B17AB0CB-4F65-4183-8157-75DB7BD7CDBE;mulle-atexit;no-cmake-loader,no-cmake-searchpath,no-dynamic-link,no-import,no-intermediate-link,no-singlephase;mulle-core-all-load,mulle-atexit
# Disable with : `mulle-sourcetree mark mulle-atexit no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-atexit no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-atexit no-cmake-sdk-<name>`
#
if( COLLECT_STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES "mulle-core-all-load")
else()
   if( NOT MULLE__ATEXIT_LIBRARY)
      foreach( _TMP_MULLE__ATEXIT_LIBRARY_TARGET mulle-core-all-load mulle-atexit)
         if( TARGET ${_TMP_MULLE__ATEXIT_LIBRARY_TARGET})
            set( MULLE__ATEXIT_LIBRARY ${_TMP_MULLE__ATEXIT_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__ATEXIT_LIBRARY)
         find_library( MULLE__ATEXIT_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_STATIC_LIBRARY_SUFFIX}
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__ATEXIT_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__ATEXIT_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_STATIC_LIBRARY_SUFFIX}
            )
         endif()
      endif()
      message( STATUS "MULLE__ATEXIT_LIBRARY is ${MULLE__ATEXIT_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__ATEXIT_LIBRARY)
         #
         # Add MULLE__ATEXIT_LIBRARY to STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-add`
         #
         list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE__ATEXIT_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__ATEXIT_ROOT "${MULLE__ATEXIT_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__ATEXIT_ROOT "${_TMP_MULLE__ATEXIT_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-atexit no-cmake-dependency`
         #
         foreach( _TMP_MULLE__ATEXIT_NAME "mulle-core-all-load" "mulle-atexit")
            set( _TMP_MULLE__ATEXIT_DIR "${_TMP_MULLE__ATEXIT_ROOT}/include/${_TMP_MULLE__ATEXIT_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__ATEXIT_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__ATEXIT_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__ATEXIT_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__ATEXIT_DIR}")
               #
               unset( MULLE__ATEXIT_DEFINITIONS)
               unset( MULLE__ATEXIT_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__ATEXIT_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__ATEXIT_DEFINITIONS})
               include( "${_TMP_MULLE__ATEXIT_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__ATEXIT_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__ATEXIT_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-atexit no-require-link`
         message( SEND_ERROR "MULLE__ATEXIT_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-atexit${CMAKE_STATIC_LIBRARY_SUFFIX}")
      endif()
   endif()
endif()


#
# Generated from sourcetree: 8FDA4226-E7FF-4BC2-818E-9245794F64B7;mulle-stacktrace;no-cmake-loader,no-cmake-searchpath,no-dynamic-link,no-import,no-intermediate-link,no-singlephase;mulle-core-all-load,mulle-stacktrace
# Disable with : `mulle-sourcetree mark mulle-stacktrace no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-stacktrace no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-stacktrace no-cmake-sdk-<name>`
#
if( COLLECT_STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES_AS_NAMES)
   list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES "mulle-core-all-load")
else()
   if( NOT MULLE__STACKTRACE_LIBRARY)
      foreach( _TMP_MULLE__STACKTRACE_LIBRARY_TARGET mulle-core-all-load mulle-stacktrace)
         if( TARGET ${_TMP_MULLE__STACKTRACE_LIBRARY_TARGET})
            set( MULLE__STACKTRACE_LIBRARY ${_TMP_MULLE__STACKTRACE_LIBRARY_TARGET})
            break()
         endif()
      endforeach()
      if( NOT MULLE__STACKTRACE_LIBRARY)
         find_library( MULLE__STACKTRACE_LIBRARY NAMES
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
            ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_STATIC_LIBRARY_SUFFIX}
            NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH NO_CMAKE_FIND_ROOT_PATH
         )
         if( NOT MULLE__STACKTRACE_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
            find_library( MULLE__STACKTRACE_LIBRARY NAMES
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
               ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_STATIC_LIBRARY_SUFFIX}
            )
         endif()
      endif()
      message( STATUS "MULLE__STACKTRACE_LIBRARY is ${MULLE__STACKTRACE_LIBRARY}")
      #
      # The order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need.
      #
      if( MULLE__STACKTRACE_LIBRARY)
         #
         # Add MULLE__STACKTRACE_LIBRARY to STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES list.
         # Disable with: `mulle-sourcetree mark mulle-stacktrace no-cmake-add`
         #
         list( APPEND STARTUP_ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE__STACKTRACE_LIBRARY})
         #
         # Inherit information from dependency.
         # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
         # Disable with: `mulle-sourcetree mark mulle-stacktrace no-cmake-inherit`
         #
         # temporarily expand CMAKE_MODULE_PATH
         get_filename_component( _TMP_MULLE__STACKTRACE_ROOT "${MULLE__STACKTRACE_LIBRARY}" DIRECTORY)
         get_filename_component( _TMP_MULLE__STACKTRACE_ROOT "${_TMP_MULLE__STACKTRACE_ROOT}" DIRECTORY)
         #
         #
         # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
         # Disable with: `mulle-sourcetree mark mulle-stacktrace no-cmake-dependency`
         #
         foreach( _TMP_MULLE__STACKTRACE_NAME "mulle-core-all-load" "mulle-stacktrace")
            set( _TMP_MULLE__STACKTRACE_DIR "${_TMP_MULLE__STACKTRACE_ROOT}/include/${_TMP_MULLE__STACKTRACE_NAME}/cmake")
            # use explicit path to avoid "surprises"
            if( IS_DIRECTORY "${_TMP_MULLE__STACKTRACE_DIR}")
               list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__STACKTRACE_DIR}")
               # we only want top level INHERIT_OBJC_DEPS, so disable them
               if( NOT NO_INHERIT_OBJC_DEPS)
                  set( NO_INHERIT_OBJC_DEPS OFF)
               endif()
               list( APPEND _TMP_INHERIT_OBJC_DEPS ${NO_INHERIT_OBJC_DEPS})
               set( NO_INHERIT_OBJC_DEPS ON)
               #
               include( "${_TMP_MULLE__STACKTRACE_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
               #
               list( GET _TMP_INHERIT_OBJC_DEPS -1 NO_INHERIT_OBJC_DEPS)
               list( REMOVE_AT _TMP_INHERIT_OBJC_DEPS -1)
               list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__STACKTRACE_DIR}")
               #
               unset( MULLE__STACKTRACE_DEFINITIONS)
               unset( MULLE__STACKTRACE_RENDEZVOUS_GLOBALS)
               include( "${_TMP_MULLE__STACKTRACE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND INHERITED_DEFINITIONS ${MULLE__STACKTRACE_DEFINITIONS})
               include( "${_TMP_MULLE__STACKTRACE_DIR}/Definitions.cmake" OPTIONAL)
               list( APPEND RENDEZVOUS_GLOBALS ${MULLE__STACKTRACE_RENDEZVOUS_GLOBALS})
               break()
            else()
               message( STATUS "${_TMP_MULLE__STACKTRACE_DIR} not found")
            endif()
         endforeach()
      else()
         # Disable with: `mulle-sourcetree mark mulle-stacktrace no-require-link`
         message( SEND_ERROR "MULLE__STACKTRACE_LIBRARY was not found in ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-core-all-load${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
${CMAKE_STATIC_LIBRARY_PREFIX}mulle-stacktrace${CMAKE_STATIC_LIBRARY_SUFFIX}")
      endif()
   endif()
endif()
