/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE__ALLOCATOR_VERSION)
# if MULLE__ALLOCATOR_VERSION < ((5 << 20) | (0 << 8) | 1)
#  error "mulle-allocator is too old"
# endif
# if MULLE__ALLOCATOR_VERSION >= ((6 << 20) | (0 << 8) | 0)
#  error "mulle-allocator is too new"
# endif
#endif

#if defined( MULLE__ATEXIT_VERSION)
# if MULLE__ATEXIT_VERSION < ((0 << 20) | (0 << 8) | 13)
#  error "mulle-atexit is too old"
# endif
# if MULLE__ATEXIT_VERSION >= ((0 << 20) | (1 << 8) | 0)
#  error "mulle-atexit is too new"
# endif
#endif

#if defined( MULLE__ATINIT_VERSION)
# if MULLE__ATINIT_VERSION < ((0 << 20) | (0 << 8) | 10)
#  error "mulle-atinit is too old"
# endif
# if MULLE__ATINIT_VERSION >= ((0 << 20) | (1 << 8) | 0)
#  error "mulle-atinit is too new"
# endif
#endif

#if defined( MULLE__DLFCN_VERSION)
# if MULLE__DLFCN_VERSION < ((0 << 20) | (0 << 8) | 11)
#  error "mulle-dlfcn is too old"
# endif
# if MULLE__DLFCN_VERSION >= ((0 << 20) | (1 << 8) | 0)
#  error "mulle-dlfcn is too new"
# endif
#endif

#if defined( MULLE__STACKTRACE_VERSION)
# if MULLE__STACKTRACE_VERSION < ((0 << 20) | (2 << 8) | 7)
#  error "mulle-stacktrace is too old"
# endif
# if MULLE__STACKTRACE_VERSION >= ((0 << 20) | (3 << 8) | 0)
#  error "mulle-stacktrace is too new"
# endif
#endif

#if defined( MULLE__THREAD_VERSION)
# if MULLE__THREAD_VERSION < ((4 << 20) | (5 << 8) | 1)
#  error "mulle-thread is too old"
# endif
# if MULLE__THREAD_VERSION >= ((5 << 20) | (0 << 8) | 0)
#  error "mulle-thread is too new"
# endif
#endif
