/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_testallocator_include_private_h__
#define _mulle_testallocator_include_private_h__

// You can tweak the following #include with these commands.
// (Use DC0E6DE2-37B0-4CCF-BF12-F0C5C7F3A994 instead of mulle-stacktrace if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-stacktrace no-header`
//    rename:             `mulle-sde dependency|library set mulle-stacktrace include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-stacktrace <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-stacktrace [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-stacktrace [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-stacktrace [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-stacktrace no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

// You can tweak the following #include with these commands.
// (Use 5A3C4A8D-C513-491E-A254-FCB2EAA4F8DE instead of mulle-atinit if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-atinit no-header`
//    rename:             `mulle-sde dependency|library set mulle-atinit include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-atinit <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-atinit [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-atinit [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-atinit [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-atinit no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-atinit/mulle-atinit.h>   // mulle-atinit

// You can tweak the following #include with these commands.
// (Use DA08D176-9F38-434B-AFCD-FD83A249E6ED instead of mulle-atexit if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-atexit no-header`
//    rename:             `mulle-sde dependency|library set mulle-atexit include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-atexit <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-atexit [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-atexit [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-atexit [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-atexit no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-atexit/mulle-atexit.h>   // mulle-atexit

#endif
