/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_testallocator_include_private_h__
#define _mulle_testallocator_include_private_h__

// remove with `mulle-sourcetree mark mulle-stacktrace no-header`
// rename with `mulle-sourcetree mark mulle-stacktrace set include whatever.h`
# include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

// remove with `mulle-sourcetree mark mulle-atinit no-header`
// rename with `mulle-sourcetree mark mulle-atinit set include whatever.h`
# include <mulle-atinit/mulle-atinit.h>   // mulle-atinit

// remove with `mulle-sourcetree mark mulle-atexit no-header`
// rename with `mulle-sourcetree mark mulle-atexit set include whatever.h`
# include <mulle-atexit/mulle-atexit.h>   // mulle-atexit

#endif
