/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_INCLUDE_FILE NONE|DISABLE.
*/

#ifndef _mulle_testallocator_include_h__
#define _mulle_testallocator_include_h__

# include <mulle-thread/mulle-thread.h>   // mulle-thread

# include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

# include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

#endif
