/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _mulle_testallocator_include_h__
#define _mulle_testallocator_include_h__

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-thread/mulle-thread.h>   // mulle-thread

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-stacktrace/mulle-stacktrace.h>   // mulle-stacktrace

// library: remove with `mark no-header`, rename with `set include`
# include <mulle-atexit/mulle-atexit.h>   // mulle-atexit

#endif
